
{% set name = "NRLMSISE-00" %}
{% set version = "0.1" %}
{% set url = "https://git.linta.de/?p=~brodo/nrlmsise-00.git;a=snapshot;h=bc9a2feba4344e74201281e563332688a4d09cc3;sf=tgz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}.tar
  url: {{ url }}

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('c') }}

test:
  requires:
    - cmake
    - {{ compiler('c') }}

  files:
    - nrlmsise-00_test.c

about:
  home: https://www.brodo.de/space/nrlmsise/
  summary: "The NRLMSIS-00 empirical atmosphere model"
  description: |
      The NRLMSIS-00 empirical atmosphere model was developed by Mike
      Picone, Alan Hedin, and Doug Drob based on the MSISE90 model.

      The MSISE90 model describes the neutral temperature and densities in
      Earth's atmosphere from ground to thermospheric heights. Below 72.5 km
      the model is primarily based on the MAP Handbook (Labitzke et al.,
      1985) tabulation of zonal average temperature and pressure by Barnett
      and Corney, which was also used for the CIRA-86. Below 20 km these
      data were supplemented with averages from the National Meteorological
      Center (NMC). In addition, pitot tube, falling sphere, and grenade
      sounder rocket measurements from 1947 to 1972 were taken into
      consideration. Above 72.5 km MSISE-90 is essentially a revised MSIS-86
      model taking into account data derived from space shuttle flights and
      newer incoherent scatter results. For someone interested only in the
      thermosphere (above 120 km), the author recommends the MSIS-86
      model. MSISE is also not the model of preference for specialized
      tropospheric work. It is rather for studies that reach across several
      atmospheric boundaries.
      (quoted from http://nssdc.gsfc.nasa.gov/space/model/atmos/nrlmsise00.html)
