{% set name = "nrlmsise" %}
{% set version = "00" %}
{% set git_rev = "bc9a2feba4344e74201281e563332688a4d09cc3" %}
{% set git_url = "https://git.linta.de/~brodo/nrlmsise-00.git" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ git_url }}
  git_rev: {{ git_rev }}

build:
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('c') }}

test:
  requires:
    - {{ compiler('c') }}

  source_files:
    - nrlmsise-00_test.c

  commands:
    # Compile the test executable for Unix-like systems
    - "$CC nrlmsise-00_test.c -I$PREFIX/include/nrlmsise-00 -L$PREFIX/lib -lnrlmsise-00 -o nrlmsise-00_test"  # [not win]

    # Compile the test executable for Windows systems
    - "%CC% nrlmsise-00_test.c -I%PREFIX%/include/nrlmsise-00 -L%PREFIX%/lib -lnrlmsise-00 -o nrlmsise-00_test.exe"  # [win]

    # Execute the compiled test executable for Unix-like systems
    - "if [ ! -f nrlmsise-00_test ]; then exit 1; fi"  # [not win]
    - "LD_LIBRARY_PATH=$PREFIX/lib ./nrlmsise-00_test"  # [not win]

    # Execute the compiled test executable for Windows systems
    - "if not exist nrlmsise-00_test.exe (exit 1)"  # [win]
    - "./nrlmsise-00_test.exe"  # [win]

about:
  home: https://www.brodo.de/space/nrlmsise/
  license: BSD-3-Clause
  license_family: BSD
  summary: 'NRLMSISE-00 is an empirical atmospheric model developed by the Naval Research Laboratory.'
  description: |
    The NRLMSISE-00 empirical atmosphere model was developed by Mike Picone, Alan Hedin, and Doug Drob. 
    It describes the neutral temperature and densities in Earth's atmosphere from ground to thermospheric heights.
  doc_url: https://www.brodo.de/space/nrlmsise/

extra:
  recipe-maintainers:
    - geoffreygarrett
