{% set name = "nrlmsise" %}
{% set version = "00" %}
{% set git_rev = "bc9a2feba4344e74201281e563332688a4d09cc3" %}
{% set git_url = "https://git.linta.de/~brodo/nrlmsise-00.git" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ git_url }}
  git_rev: {{ git_rev }}
  patches:
    - 0001_new_path_include_for_conda_package_test.patch

build:
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('c') }}

test:
  requires:
    - {{ compiler('c') }}

  files:
    - test_nrlmsise_unix.sh         # [not win]
    - test_nrlmsise_windows.bat     # [win]

  source_files:
    - nrlmsise-00_test.c

  commands:
    - bash ./test_nrlmsise_unix.sh  # [not win]
    - test_nrlmsise_windows.bat     # [win]

about:
  home: https://www.brodo.de/space/nrlmsise/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'NRLMSISE-00 is an empirical atmospheric model developed by the Naval Research Laboratory.'
  description: |
    The NRLMSISE-00 empirical atmosphere model was developed by Mike Picone, Alan Hedin, and Doug Drob. 
    It describes the neutral temperature and densities in Earth's atmosphere from ground to thermospheric heights.
  doc_url: https://www.brodo.de/space/nrlmsise/
  doc_source_url: https://git.linta.de/~brodo/nrlmsise-00.git/plain/DOCUMENTATION?id={{ git_rev }}

extra:
  recipe-maintainers:
    - geoffreygarrett
